[window]
opacity = 0.8

[colors.primary]
foreground = "#CDD6F4"
background = "#1E1E2E"

[cursor]
style = { shape = "Beam", blinking = "always" }
smooth_motion = true
smooth_motion_factor = 0.7
smooth_motion_spring = 0.3
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0

